"""
GraphIngest SDK: run() — INTERNAL

This module is used by the platform to create execution environments.
End users should NOT call run() directly. Instead, use deploy() to push
code to the platform, which auto-generates the entrypoint internally.

Internal usage (auto-generated by platform):
    from graphingest import run
    app = run()
"""

from __future__ import annotations

import json
import logging
import os
import time
import traceback
import uuid
from typing import Any, Optional

try:
    from flask import Flask, jsonify, request
except ImportError:
    Flask = None  # type: ignore

logger = logging.getLogger("graphingest.serve")


def run(
    *,
    functions: Optional[list] = None,
    framework: str = "flask",
) -> Flask:
    """Create an HTTP application that serves @node functions.

    Args:
        functions: Optional list of @node-decorated functions to execute.
                   If None, serves ALL functions registered via @node.
        framework: HTTP framework to use (currently only "flask").

    Returns:
        A Flask WSGI application.
    """
    if Flask is None:
        raise ImportError(
            "Flask is required for run(). Install it: pip install flask"
        )

    from .task import _node_registry

    # Build the function lookup table
    registry: dict[str, Any] = {}

    if functions is not None:
        for fn in functions:
            key = getattr(fn, "_node_key", None) or fn.__name__
            original = getattr(fn, "_original_fn", fn)
            registry[key] = original
    else:
        registry.update(_node_registry)

    app = Flask(__name__)
    app.config["registry"] = registry

    worker_id = f"worker-{uuid.uuid4().hex[:8]}"

    @app.route("/health", methods=["GET"])
    def health():
        return jsonify({
            "status": "healthy",
            "worker_id": worker_id,
            "registered_functions": sorted(registry.keys()),
        })

    @app.route("/api/execute", methods=["POST"])
    def _handle_execute():
        body = request.get_json(force=True)
        task_key = body.get("taskKey", "")
        task_run_id = body.get("taskRunId", "")
        flow_run_id = body.get("flowRunId", "")
        input_data = body.get("inputData", {})
        map_index = body.get("mapIndex")

        logger.info(f"Executing task: {task_key} (run: {task_run_id})")

        start = time.monotonic()

        task_fn = registry.get(task_key)
        if task_fn is None:
            return jsonify({
                "status": "failed",
                "task_run_id": task_run_id,
                "error": f"Task '{task_key}' not found in registered functions. "
                         f"Available: {sorted(registry.keys())}",
            }), 200

        try:
            if map_index is not None and isinstance(input_data, dict):
                result = task_fn(**input_data, map_index=map_index)
            elif map_index is not None:
                result = task_fn(input_data, map_index=map_index)
            elif isinstance(input_data, dict):
                result = task_fn(**input_data)
            else:
                result = task_fn(input_data)

            duration_ms = int((time.monotonic() - start) * 1000)

            return jsonify({
                "status": "completed",
                "task_run_id": task_run_id,
                "result_data": result,
                "duration_ms": duration_ms,
            })

        except Exception as exc:
            duration_ms = int((time.monotonic() - start) * 1000)
            logger.exception(f"Task {task_key} failed: {exc}")
            return jsonify({
                "status": "failed",
                "task_run_id": task_run_id,
                "error": str(exc),
                "error_type": type(exc).__name__,
                "traceback": traceback.format_exc(),
                "duration_ms": duration_ms,
            }), 200

    @app.route("/api/functions", methods=["GET"])
    def list_functions():
        """Discovery endpoint — platform calls this to see what's registered."""
        funcs = []
        for key, fn in registry.items():
            funcs.append({
                "key": key,
                "doc": (fn.__doc__ or "").strip(),
                "module": fn.__module__,
            })
        return jsonify({"functions": funcs})

    logger.info(f"Registered {len(registry)} functions: {sorted(registry.keys())}")

    return app
